name: CI on self-hosted runner

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Python version
        run: |
          py --version
          where py

      - name: Install dependencies
        run: py -m pip install -r requirements.txt

      - name: Run tests
        run: py -m pytest
